export var __esModule: boolean;
export var Alignment: {} | undefined;
export var Directions: {} | undefined;
export var Positions: {} | undefined;
export var ScrollMode: {} | undefined;
export var D3EasingFunctions: {} | undefined;
export var Alignment: any;
export var Directions: any;
export var Positions: any;
export var ScrollMode: any;
export var D3EasingFunctions: any;
